export interface Exercise {
  id: string
  title: string
  description: string
  duration: string
  instructions: string[]
  benefits: string[]
  recommendedForMoods: number[] // 1-5 mood values
  difficulty: "beginner" | "intermediate" | "advanced"
  youtubeUrl?: string // Added YouTube URL field
}

export const EXERCISES: Exercise[] = [
  {
    id: "box-breathing",
    title: "Box Breathing",
    description: "A simple breathing pattern that helps calm the nervous system and reduce stress",
    duration: "5 minutes",
    recommendedForMoods: [2, 3],
    difficulty: "beginner",
    instructions: [
      "Find a comfortable seated position",
      "Breathe in slowly through your nose for 4 counts",
      "Hold your breath for 4 counts",
      "Exhale slowly through your mouth for 4 counts",
      "Hold your breath for 4 counts",
      "Repeat this cycle for 5 minutes",
    ],
    benefits: ["Reduces stress", "Improves focus", "Lowers heart rate", "Calms anxiety"],
    youtubeUrl: "https://www.youtube.com/embed/n6RbW2BkoH4", // Added relevant video
  },
  {
    id: "478-breathing",
    title: "4-7-8 Breathing",
    description: "A relaxing breath technique that helps you fall asleep and manage anxious thoughts",
    duration: "3-5 minutes",
    recommendedForMoods: [1, 2],
    difficulty: "beginner",
    instructions: [
      "Sit or lie down in a comfortable position",
      "Place the tip of your tongue behind your upper front teeth",
      "Exhale completely through your mouth making a whoosh sound",
      "Close your mouth and inhale quietly through your nose for 4 counts",
      "Hold your breath for 7 counts",
      "Exhale completely through your mouth for 8 counts",
      "Repeat this cycle 3-4 times",
    ],
    benefits: ["Promotes sleep", "Reduces anxiety", "Manages stress response", "Calms the mind"],
    youtubeUrl: "https://www.youtube.com/embed/1739_m8_8E", // Added relevant video
  },
  {
    id: "body-scan",
    title: "Body Scan Meditation",
    description: "A mindfulness practice that helps you connect with physical sensations and release tension",
    duration: "10-15 minutes",
    recommendedForMoods: [2, 3],
    difficulty: "intermediate",
    instructions: [
      "Lie down or sit comfortably in a quiet space",
      "Close your eyes and take three deep breaths",
      "Start by noticing sensations in your toes",
      "Slowly move your attention up through your feet, legs, torso, arms, and head",
      "Notice any tension, warmth, coolness, or tingling without judgment",
      "Breathe into any areas of tension and imagine them relaxing",
      "Complete the scan at your own pace",
    ],
    benefits: ["Releases physical tension", "Improves body awareness", "Reduces stress", "Promotes relaxation"],
    youtubeUrl: "https://www.youtube.com/embed/D8oKWQiEWYs", // Added relevant video
  },
  {
    id: "5-senses",
    title: "5 Senses Grounding",
    description: "A grounding technique that brings you back to the present moment during anxious thoughts",
    duration: "5 minutes",
    recommendedForMoods: [1, 2],
    difficulty: "beginner",
    instructions: [
      "Pause and take a deep breath",
      "Notice 5 things you can see around you",
      "Notice 4 things you can physically feel (texture, temperature)",
      "Notice 3 things you can hear",
      "Notice 2 things you can smell (or think of favorite scents)",
      "Notice 1 thing you can taste (or imagine a favorite taste)",
      "Take a few more deep breaths",
    ],
    benefits: ["Stops panic spirals", "Grounds you in the present", "Reduces anxiety", "Easy to do anywhere"],
  },
  {
    id: "progressive-relaxation",
    title: "Progressive Muscle Relaxation",
    description: "Systematically tense and release muscle groups to reduce physical stress",
    duration: "10-15 minutes",
    recommendedForMoods: [2, 3],
    difficulty: "intermediate",
    instructions: [
      "Find a comfortable position lying down or sitting",
      "Starting with your feet, tense the muscles tightly for 5 seconds",
      "Release the tension and notice the feeling of relaxation",
      "Move up to your calves, thighs, stomach, hands, arms, shoulders, and face",
      "Tense each muscle group for 5 seconds, then release for 10 seconds",
      "Notice the difference between tension and relaxation",
      "End with a few deep breaths",
    ],
    benefits: ["Releases physical tension", "Improves sleep quality", "Reduces muscle pain", "Lowers stress levels"],
  },
  {
    id: "mindful-breathing",
    title: "Mindful Breathing",
    description: "Simple awareness of your natural breath to anchor yourself in the present",
    duration: "5-10 minutes",
    recommendedForMoods: [3, 4],
    difficulty: "beginner",
    instructions: [
      "Sit comfortably with your back supported",
      "Close your eyes or soften your gaze",
      "Notice your natural breathing pattern without changing it",
      "Feel the sensation of air entering and leaving your nose",
      "When your mind wanders, gently return focus to your breath",
      "Continue for 5-10 minutes",
      "End by slowly opening your eyes",
    ],
    benefits: ["Improves concentration", "Reduces mind chatter", "Lowers stress", "Accessible for beginners"],
  },
  {
    id: "alternate-nostril",
    title: "Alternate Nostril Breathing",
    description: "A yogic breathing technique that balances energy and calms the nervous system",
    duration: "5-8 minutes",
    recommendedForMoods: [2, 3],
    difficulty: "intermediate",
    instructions: [
      "Sit comfortably with your spine straight",
      "Rest your left hand on your lap",
      "Bring your right hand to your nose",
      "Close your right nostril with your thumb, inhale through the left for 4 counts",
      "Close both nostrils, hold for 4 counts",
      "Release your thumb, exhale through right nostril for 4 counts",
      "Inhale through right nostril for 4 counts",
      "Close both, hold for 4 counts",
      "Release left nostril, exhale for 4 counts",
      "This completes one cycle - repeat 5-10 times",
    ],
    benefits: [
      "Balances left and right brain hemispheres",
      "Reduces anxiety",
      "Improves focus",
      "Calms the mind before sleep or study",
    ],
  },
  {
    id: "loving-kindness",
    title: "Loving-Kindness Meditation",
    description: "A compassion meditation that cultivates positive feelings towards yourself and others",
    duration: "10-15 minutes",
    recommendedForMoods: [2, 3, 4],
    difficulty: "intermediate",
    instructions: [
      "Sit comfortably and close your eyes",
      "Take a few deep breaths to settle",
      "Begin by directing kindness to yourself: 'May I be happy. May I be healthy. May I be safe. May I live with ease.'",
      "Repeat these phrases slowly, feeling the intention behind each word",
      "Next, bring to mind someone you love and direct the same wishes to them",
      "Then think of a neutral person - someone you see but don't know well",
      "If you're ready, extend these wishes to someone you find difficult",
      "Finally, extend kindness to all beings everywhere",
      "Rest in the feeling of warmth and connection for a few moments",
    ],
    benefits: [
      "Increases self-compassion",
      "Reduces self-criticism",
      "Improves relationships",
      "Cultivates positive emotions",
    ],
  },
  {
    id: "visualization",
    title: "Safe Place Visualization",
    description: "Create a mental sanctuary you can visit anytime you need comfort and calm",
    duration: "8-12 minutes",
    recommendedForMoods: [1, 2, 3],
    difficulty: "beginner",
    instructions: [
      "Find a comfortable position and close your eyes",
      "Take three deep, calming breaths",
      "Imagine a place where you feel completely safe and peaceful - real or imaginary",
      "Notice the details: What do you see? What colors surround you?",
      "What sounds can you hear? Birds, water, wind, silence?",
      "What can you feel? Warm sun, cool breeze, soft ground?",
      "What can you smell? Fresh air, flowers, ocean?",
      "Spend time exploring this safe place with all your senses",
      "Know that you can return here whenever you need comfort",
      "When ready, take a deep breath and slowly open your eyes",
    ],
    benefits: [
      "Creates a mental refuge",
      "Reduces panic and anxiety",
      "Improves emotional regulation",
      "Builds coping resources",
    ],
  },
  {
    id: "walking-meditation",
    title: "Mindful Walking",
    description: "Bring mindfulness to movement by focusing on each step with full awareness",
    duration: "10-20 minutes",
    recommendedForMoods: [3, 4],
    difficulty: "beginner",
    instructions: [
      "Find a safe path where you can walk undisturbed - indoors or outdoors",
      "Stand still and take three deep breaths",
      "Begin walking at a natural, slightly slower pace",
      "Focus on the sensation of your feet touching the ground",
      "Notice the lifting, moving, and placing of each foot",
      "Feel your weight shift from one leg to the other",
      "Be aware of your breath as you walk",
      "If your mind wanders, gently return attention to your steps",
      "Notice your surroundings with soft awareness",
      "Walk for 10-20 minutes, staying present with each step",
    ],
    benefits: [
      "Combines movement with mindfulness",
      "Reduces restlessness",
      "Improves body awareness",
      "Great for active minds",
    ],
  },
  {
    id: "belly-breathing",
    title: "Diaphragmatic Breathing",
    description: "Deep belly breathing that activates your body's natural relaxation response",
    duration: "5-10 minutes",
    recommendedForMoods: [1, 2, 3],
    difficulty: "beginner",
    instructions: [
      "Lie down or sit comfortably with one hand on your chest and one on your belly",
      "Take a normal breath and notice which hand moves more",
      "Now breathe in slowly through your nose, letting your belly expand like a balloon",
      "Your chest should stay relatively still while your belly rises",
      "Exhale slowly through your mouth, feeling your belly fall",
      "Continue for 5-10 minutes, keeping breaths slow and deep",
      "If you feel dizzy, return to normal breathing",
    ],
    benefits: [
      "Activates relaxation response",
      "Reduces physical tension",
      "Lowers blood pressure",
      "Improves oxygen flow",
    ],
  },
  {
    id: "counting-meditation",
    title: "Counting Meditation",
    description: "A focus meditation that uses counting to anchor your wandering mind",
    duration: "10-15 minutes",
    recommendedForMoods: [3, 4],
    difficulty: "beginner",
    instructions: [
      "Sit in a comfortable position with your eyes closed or softly gazing down",
      "Take a few deep breaths to settle",
      "Begin counting your breaths silently: inhale (1), exhale (1), inhale (2), exhale (2)",
      "Continue counting up to 10, then start again at 1",
      "If you lose count or your mind wanders, gently start back at 1 without judgment",
      "The goal isn't to reach 10 perfectly - it's to notice when your mind wanders",
      "Continue for 10-15 minutes",
      "End by taking three deep breaths before opening your eyes",
    ],
    benefits: ["Improves concentration", "Trains attention", "Reduces mental chatter", "Builds meditation skills"],
  },
  {
    id: "gratitude-reflection",
    title: "Gratitude Reflection",
    description: "A practice of appreciating the good things in your life to shift perspective",
    duration: "5-8 minutes",
    recommendedForMoods: [2, 3, 4, 5],
    difficulty: "beginner",
    instructions: [
      "Sit comfortably and take a few calming breaths",
      "Bring to mind three things you're grateful for today - they can be simple",
      "For each one, spend a moment really feeling the appreciation",
      "Notice where you feel gratitude in your body - perhaps warmth in your chest",
      "Consider why each thing matters to you",
      "Think of one person you're grateful for and why",
      "Reflect on one thing about yourself you appreciate",
      "Rest in this feeling of appreciation for a few moments",
      "Take a deep breath and open your eyes when ready",
    ],
    benefits: [
      "Shifts focus from negative to positive",
      "Improves mood",
      "Increases life satisfaction",
      "Builds resilience",
    ],
  },
  {
    id: "finger-breathing",
    title: "Hand Tracing Breathing",
    description: "A simple tactile breathing exercise perfect for anxious moments",
    duration: "3-5 minutes",
    recommendedForMoods: [1, 2],
    difficulty: "beginner",
    instructions: [
      "Hold one hand in front of you with fingers spread",
      "Use the index finger of your other hand to trace your hand",
      "Starting at the base of your thumb, breathe in as you trace up the thumb",
      "Breathe out as you trace down the other side",
      "Continue: breathe in going up each finger, breathe out going down",
      "Trace all five fingers, focusing on your breath and the sensation of touch",
      "Repeat with the other hand if desired",
      "Notice how your breathing has slowed and deepened",
    ],
    benefits: [
      "Easy to do anywhere discreetly",
      "Combines breath with touch",
      "Quick anxiety relief",
      "Good for beginners",
    ],
  },
  {
    id: "mindful-observation",
    title: "Mindful Object Observation",
    description: "Practice present-moment awareness by deeply observing a single object",
    duration: "5-7 minutes",
    recommendedForMoods: [3, 4],
    difficulty: "beginner",
    instructions: [
      "Choose a natural object nearby - a flower, leaf, stone, or fruit",
      "Hold it in your hand or place it in front of you",
      "Observe it as if you've never seen anything like it before",
      "Notice its colors, textures, patterns, and shape in detail",
      "Feel its weight, temperature, and texture",
      "If it has a scent, smell it mindfully",
      "Let yourself be fully absorbed in this simple act of observation",
      "Notice any judgments or thoughts that arise, then return to observing",
      "After 5-7 minutes, reflect on what you noticed",
    ],
    benefits: [
      "Trains present-moment awareness",
      "Breaks rumination cycles",
      "Develops observation skills",
      "Calms busy mind",
    ],
  },
]

export function getRecommendedExercises(recentMoodAverage: number): Exercise[] {
  return EXERCISES.filter((exercise) => exercise.recommendedForMoods.includes(Math.round(recentMoodAverage)))
}

export function getExercisesByDifficulty(difficulty: "beginner" | "intermediate" | "advanced"): Exercise[] {
  return EXERCISES.filter((exercise) => exercise.difficulty === difficulty)
}
